# Generated by Django 5.1.5 on 2025-03-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen_fondo', models.ImageField(upload_to='historias/')),
            ],
        ),
        migrations.CreateModel(
            name='Secuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('imagen_fondo', models.ImageField(upload_to='secuelas/')),
                ('imagen_personaje', models.ImageField(upload_to='personajes/')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secuelas', to='blog.historia')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
