# Generated by Django 5.1.5 on 2025-04-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_personaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secuela',
            name='historia',
        ),
    ]
