# Generated by Django 5.1.5 on 2025-04-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_secuela_historia'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuela',
            name='mini_historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SecuelaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='secuelas/galeria/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('secuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='blog.secuela')),
            ],
        ),
    ]
