# Generated by Django 5.1.5 on 2025-04-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_secuela_mini_historia_secuelaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='caracter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personaje',
            name='curiosidades',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='stamina',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personaje',
            name='velocidad',
            field=models.IntegerField(default=0),
        ),
    ]
