# Generated by Django 5.1.5 on 2025-05-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_personaje_caracter_personaje_curiosidades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='contenido_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='contenido_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historia',
            name='titulo_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
