# Generated by Django 5.1.5 on 2025-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_historia_contenido_en_historia_contenido_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='descripcion_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='descripcion_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaje',
            name='nombre_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
