# Generated by Django 5.1.5 on 2025-07-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_personaje_descripcion_en_personaje_descripcion_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secuela',
            name='contenido_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuela',
            name='contenido_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuela',
            name='mini_historia_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuela',
            name='mini_historia_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='secuela',
            name='titulo_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='secuela',
            name='titulo_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
